### ISSUE TITLE
Module Install 

### ISSUE THREAD

**Issue by DarkkingDraco** [p4535992/foundryvtt-forien-unidentified-items#2]
The module no longer appears in the module listing within Foundry on the Forge. 
I think this is due to the version number including the v at start.

**Comment by p4535992** [comment]
This is not the official repository this is why you do not see this on the module list, you must manually install with the json manifest

https://github.com/p4535992/foundryvtt-forien-unidentified-items/releases/download/v1.0.0/module.json

"v1.0.0" is just a label on github not on the manifest json.
